spring.application.name=gestion-nomina

# Configuración de SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=gestion_nomina;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=admin123..
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración de MongoDB
spring.data.mongodb.uri=mongodb+srv://eliecer:prueba123@cluster0.pdj4glq.mongodb.net/gestion_nomina?retryWrites=true&w=majority
spring.data.mongodb.database=gestion_nomina

# Configuración de Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none

# Configuración de logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
